language: php
addons:
  apt:
    packages:
      - ant
php:
    - 7.2
    - 7.3
    - 7.4
    - 8.0

before_script:
    - composer install --prefer-dist --dev

script:
    - ant lint
    - ./vendor/bin/phpunit --configuration phpunit.xml.dist
    - ./vendor/bin/phpcs --standard=phpcs.xml  src/

notifications:
  email: false
