language: php
addons:
  apt:
    packages:
      - ant
php:
    - 7.2
    - 7.3
    - 7.4

before_script:
    - composer install --prefer-dist --dev
    - mkdir -p "$HOME/bin"
    - export PATH="$HOME/bin:$PATH"
    - if [ ! -d "$HOME/.phive" ]; then mkdir "$HOME/.phive"; fi
    - if [ ! -f "$HOME/.phive/phive.phar" ]; then ant getphive; mv phive.phar "$HOME/.phive/"; fi
    - install --mode=0755 -T "$HOME/.phive/phive.phar" "$HOME/bin/phive"

script:
    - ant lint
    - ant getphive
    - ant install-tools
    - ./tools/phpunit --configuration phpunit.xml.dist

notifications:
  email: false
